### ISSUE TITLE
Problemer med jorder 

### ISSUE THREAD

**Issue by Inderoy20** [MapsOfNorway/rennebugs#1]
@OlaHaldor 

Er nå problem med å se hav som er på jordene og hva som må gjøres på de 

![20220714_195958](https://user-images.githubusercontent.com/109306940/179051310-629cbb6a-588e-4da8-82f6-0c1155c91857.jpg)

**Comment by OlaHaldor** [comment]
Kan du utdype?

**Comment by Inderoy20** [comment]
> https://youtu.be/QwMQQhX7hmo

**Comment by OlaHaldor** [comment]
Her er det skjedd noe rart ja. Kan ikke si jeg på stående fot vet hva eller hvorfor.
Får du noe feilmelding i loggen?

**Comment by Inderoy20** [comment]
Lit usikker på hva du mener med loggen Men jeg er borte i 2 uker på ferie så har ikke mulighet til å kjeke det nå .

**Comment by jornil03** [comment]
Trodde jeg hadde samme problemet som du, men det viser seg at du må vente mens det står «loading maps» det tar litt tid mellom valgene du fåretar deg😎

**Comment by OlaHaldor** [comment]
Jeg greier ikke se at dette er noe på grunn av dette kartet spesifik - men heller noe med Giants Engine/Farming Sim generelt med store kart.
