### ISSUE TITLE
Norigard yard trees (spruce id 904105) not cuttable/deletable

### ISSUE THREAD

**Issue by Leo82112** [MapsOfNorway/rennebugs#100]
Norigard yard tree (id 904105) in front of houses not cuttable/deletable. I first encountered this as I tried cutting it with dfm cfb-16 from Giant's DFM tool mod as it was wobbling on my main save game. After that it said "you do not have permissoion to cut this tree or something". Tested lowering and raising terrain and there was lots of tree trunk below yard level. Tried using lumberjack, tree-b-gone, trex600, tree remover mods. It was just and object that was not cuttable Chainsaw had grey cutting symbol over is and chainsaw just disappeared when pressing cut button. Tested on new game with only trex 600 and lumberjack mods (without them it was not cuttable) and after raising terrain around it and using trex600 from top down I managed to grind it to about 1 meter high stump that did not react to anything.
I tested deleting it from rennebu.i3d with editor and there was different type of spruce in it's place which was fully cuttable and deletable.

Also similar issues with elms at the end of field where my helpers kept crashing into, but they were deletable with those mods after spinning around and searching right spot. Needed to put mulcher next to trunk and they were grindable Going straight to them just crashed in to them. With chainsaw I could only cut few limbs off the elms with lumberjack and long range chainsaw mods.

I know this is not of a big deal, but decided to inform you anyway as removing it appears game runs better near Norigard yard without those trees.

![image](https://user-images.githubusercontent.com/110819943/183399067-5524f7c9-c41e-4875-adf7-10598d135eb0.png)

![image](https://user-images.githubusercontent.com/110819943/183398932-3767c67b-7e37-4519-a231-1471ae635178.png)

**Comment by OlaHaldor** [comment]
I will have a look :)
I was not aware it couldn't be cut.

**Comment by OlaHaldor** [comment]
Changes to trees will require a new savegame sadly. I've added a default, smaller tree
