### ISSUE TITLE
Easier dedicated server support

### ISSUE THREAD

**Issue by P945684** [MapsOfNorway/rennebugs#101]
Hi
I am not a experienced server manager, but a easier way to add the map to the dedicated server would be appreciated. Here are my "issues" that is reported by my Nitrado server

![Rennebu v1 0 0 1](https://user-images.githubusercontent.com/111072026/184165668-f35bbbaf-846d-426a-9d78-bf02b12d248d.png)

**Comment by OlaHaldor** [comment]
I can't do anything about how easy or not it is to add to a dedicated server. 

The issues you see are non critical for the map to work. And the issues regarding file sizes basically means the game does not officially support/recommend it, all though it works without issues.

**Comment by P945684** [comment]
By uploading a savegame to the server, it started right away! The problem was me mot the map

I will close this one now
