### ISSUE TITLE
Selling at joker shop

### ISSUE THREAD

**Issue by isak2109** [MapsOfNorway/rennebugs#102]
tried selling salad pallets at the shop, putting the pallet in different locations and did not want to sell anywhere in the area
![20220812184558_1](https://user-images.githubusercontent.com/111139393/184405639-d14c0919-b9bd-436e-8a26-3dc03043fd6e.jpg)

**Comment by OlaHaldor** [comment]
Could you press F5 (might need developer mode) to show the collision box?
Would be interesting to see where it is compared to this specific trailer.

**Comment by OlaHaldor** [comment]
I have made the trigger area larger. Hopefully that works out for you now with the future patch.
