### ISSUE TITLE
Jorde funk itj.

### ISSUE THREAD

**Issue by Makkus08** [MapsOfNorway/rennebugs#103]
![image](https://user-images.githubusercontent.com/109968073/184390860-9e50b783-914c-4b33-b92b-88b11f1b0546.png)

Får itj te å bruk ai hær.
 Jorde 41

**Comment by OlaHaldor** [comment]
Hvilke mods bruker du?
Prøv nytt savegame uten andre mods - funker det da?

Prøv eventuelt savegamet ditt uten noen mods - funker det?

**Comment by Makkus08** [comment]
Æ kan sikkert prøv ja. Men det funka med tresking da. Men ja. Kan sjekke

**Comment by OlaHaldor** [comment]
Jeg prøvde på nytt savegame senest i går kveld på stream, ingen problemer med ai.

det kom imidlertid frem at flere opplever noe av det du nevner i andre maps også, ikke bare Rennebu.

**Comment by OlaHaldor** [comment]
Har du fått testet noe mer, noe mer feedback å komme med?

**Comment by OlaHaldor** [comment]
Jeg har testet litt default kart og andre mods kart nå. Jeg får samme feil der. Så dette er et Giants-problem, ikke Rennebu-spesifikt.
Jeg ville rapportert det til Giants.
