### ISSUE TITLE
Product prices

### ISSUE THREAD

**Issue by odysseus-1** [MapsOfNorway/rennebugs#107]
Prices were balanced in the base game but the values in "maps_filltypes.xml" for Rennebu were not.

Sunflower max price: 2418
Sunflower oil (needs 2 of the base product): 4794 (not worth it)

maps_filltypes.xml for Rennebu
Sunflower 0.673
Sunflower Oil 1.35

maps_filltypes.xml for the French base map
Sunflower 0.673
Sunflower Oil 1.78

There are other cases that throw the balance off (1st price from Rennebu map, 2nd from French map)
Canola 0.603 - 0.603
Canola oil 1.35 - 1.64

Eggs 1.5 - 1.12

**Comment by OlaHaldor** [comment]
Fixed
