### ISSUE TITLE
(un)load points not marked on barn buildings

### ISSUE THREAD

**Issue by b-gyula** [MapsOfNorway/rennebugs#108]
(Un)load points not marked for barn buildings v1.0.0.1

- [x] wool load point of Ivar sheep barn
- [x] wool load point of Bergtun old sheep barn
- [x] grass/hay unload point for Bruholt cow barn

Also for the Ivar sheep barn the 10000l food storage seems to be very small compared to feeding 200 sheeps and and that Bergtun old sheep barn has 1000000l (for also 200 sheeps)

If you throw any hint how, I would volunteer to fix these! 
I know food capacity is in the xml I just don't know if it's created / updated using some editor.

**Comment by OlaHaldor** [comment]
Thanks, that's great feedback. Easy to overlook things when there's so many moving parts. :) 
I will take care of it, and there will be an update (some time, don't know _when_ ) 

Until then, you could mod the buildings for your own sake if you like, by opening the xml file in a text editor. I recommend Notepad++, Sublime Text or VS Code.

**Comment by OlaHaldor** [comment]
Bruholt cow barn has an icon inside. Don't see a reason to add ground markers. The trigger area is already big enough.
![image](https://user-images.githubusercontent.com/60529378/185704134-52302547-6d0b-44cd-9626-0263abdeda48.png)

Bergtun and Ivar sheep barn markers added. Closing and marking as fixed.
Will be available in a future update.

**Comment by b-gyula** [comment]
Bruholt cow barn was my mistake, I've also found! Sorry.
Thanks!
