### ISSUE TITLE
Bergtun old sheep barn can store only 4 produced wool pallets

### ISSUE THREAD

**Issue by b-gyula** [MapsOfNorway/rennebugs#110]
Once 4 wool have been produced An error message is displayed:
![Bergtun old sheep barn wool spawn error msg](https://user-images.githubusercontent.com/27079815/185264824-609aba90-06a6-4b85-a507-501ce0df5700.gif)

It is weird, because the FS22_BuildingsOfNorway/xml/bergtun_barn_old.xml contains
```xml
<pallets fillType="WOOL" maxNumPallets="18">
  <palletTrigger node="palletTrigger"/>
  <spawnPlaces>
  <spawnPlace startNode="palletArea1Start" endNode="palletArea1End"/>
  <spawnPlace startNode="palletArea2Start" endNode="palletArea2End"/>
  <spawnPlace startNode="palletArea3Start" endNode="palletArea3End"/>
  </spawnPlaces>
</pallets>
```

**Comment by OlaHaldor** [comment]
That is indeed strange. In my own testing I've had at least 8 maybe 10 pallets waiting for pickup. Is there anything else there, blocking the spawn area? Like a tool or a vehicle? 

Will investigate.

**Comment by b-gyula** [comment]
Nothing was blocking:
![Bergtun old sheep barn wool spawn error](https://user-images.githubusercontent.com/27079815/185448390-8c5ea877-efb0-44f1-b844-426daf254cb9.jpg)

**Comment by OlaHaldor** [comment]
I found the issue and fixed it. Available in a future update. :)
