### ISSUE TITLE
Soybeans Missing From Crop List

### ISSUE THREAD

**Issue by Dylan-M** [MapsOfNorway/rennebugs#113]
I couldn't figure out why field 119 wouldn't show me the crop state, then I realized it is because Soybeans aren't in the crop list for the map.
![fsScreen_2022_08_21_18_53_55](https://user-images.githubusercontent.com/545408/185814217-f0e38443-7b83-4dd2-873b-8f67fea7c364.png)

**Comment by OlaHaldor** [comment]
Is this an old save with the 1.0.0.1 update? Or is it a new savegame?

**Comment by Dylan-M** [comment]
Old save with the update. I wasn't aware you pulled Soybeans out. I'll just use Easy Dev tools to crop swap. :D

**Comment by OlaHaldor** [comment]
Alright! Closing :)
