### ISSUE TITLE
Two Fields with no Numbers

### ISSUE THREAD

**Issue by Dylan-M** [MapsOfNorway/rennebugs#114]
Just north of field 138 are 2 fields that do not have field numbers

![fsScreen_2022_08_11_19_30_53](https://user-images.githubusercontent.com/545408/185814252-15f44b8c-c59e-4b20-bb57-955528b7efee.png)
.

**Comment by OlaHaldor** [comment]
Correct. You can use them if you like. Or not. :) planned to make more of these, just haven't got there for the rest. :)
