### ISSUE TITLE
Texture fail on Bergtun barn?

### ISSUE THREAD

**Issue by Johansen02** [MapsOfNorway/rennebugs#117]
I think the Bergtun sheep barn got a texture fail after the new FS22 patch.
![Farming Simulator 22 Screenshot 2022 08 22 - 17 13 33 10](https://user-images.githubusercontent.com/111768222/185957064-3fa10251-149d-4c28-b6a2-97825d0db650.png)

**Comment by OlaHaldor** [comment]
I guess the patch you mention is 1.7?
I will have a look. This is a brand new issue to me.

**Comment by OlaHaldor** [comment]
I've been in touch with Giants; they say it's a known problem and will be fixed. So I won't fix anything on my end this round.
Might have to make a fix for the future (and will have to for future console release)

**Comment by OlaHaldor** [comment]
Leaving this open as a reminder until Giants' patch for these issues is out.

**Comment by OlaHaldor** [comment]
It's been sorted with the latest patch from Giants.
