### ISSUE TITLE
No accsess to Field 117

### ISSUE THREAD

**Issue by Vansan85** [MapsOfNorway/rennebugs#118]
Hallo,

there is a part of field 117, where you have no accses to work.

![Field 117](https://user-images.githubusercontent.com/97761944/186159336-59bdafec-e962-4adf-aacf-77869918e6c3.jpg)

**Comment by Vansan85** [comment]
Also Field 
![Field 5](https://user-images.githubusercontent.com/97761944/186513125-d99f4cda-a572-4f9e-8f13-8d1714990546.jpg)
5

**Comment by Vansan85** [comment]
Also Field 23
![Uploading Field 23.png…]()

**Comment by Vansan85** [comment]
Also Field 72
![Feld 72](https://user-images.githubusercontent.com/97761944/186516663-e2b5b3e0-45ac-4cca-a116-9c54a667a4c4.jpg)

**Comment by OlaHaldor** [comment]
Do you own the field or is it a contract?

**Comment by Vansan85** [comment]
Contract
Local
every time

**Comment by OlaHaldor** [comment]
Could you, just for the purpose of testing - don't save the game unless you like to:
buy the field, see if it behaves the same way then.

If you find it's only in the case of doing a contract I urge you to report it to Giants. There's nothing I can change with the map as far as I know. Fields are thoroughly separated with huge gaps already.

**Comment by Vansan85** [comment]
With contract there is the Error. Field 37

![F37 Contract](https://user-images.githubusercontent.com/97761944/187089548-dd9b5eb4-33ea-4b40-a5f7-b84fb649cebb.jpg)

When i bought the field it is OK

![F37 bought the field](https://user-images.githubusercontent.com/97761944/187089546-6db0df90-1bba-4f1c-894a-163c5e5aa453.jpg)

**Comment by OlaHaldor** [comment]
Okay, this is very interesting.. I think Giants should be made aware of this. Since you have first hand experience with the issue, I suggest you write to them [on their feedback site](https://feedback.giants-software.com/).

**Comment by OlaHaldor** [comment]
If there's no news about this, I'll close the ticket. Let me know within a week?
