### ISSUE TITLE
Traffic Jam next to field 62

### ISSUE THREAD

**Issue by Vansan85** [MapsOfNorway/rennebugs#119]
Hallo, 

there is everytime a traffic jam next to fiel 62.
Sometimes the first car drives trough, but the next stop again

![Traffic Jam Field 62](https://user-images.githubusercontent.com/97761944/186165359-c6a25e37-68e7-45dc-8fd2-5ac39060987d.jpg)

**Comment by OlaHaldor** [comment]
It will be fixed in a coming update.

**Comment by mrush842** [comment]
On a new save I've noticed this is still happening, has this been patched in the most recent version?

**Comment by OlaHaldor** [comment]
It's not been published. I'm working on preparing the map for new placeables still. :)
