### ISSUE TITLE
Svart flimring 

### ISSUE THREAD

**Issue by Tractorgay** [MapsOfNorway/rennebugs#120]
Iblant korte svarte forstyrrelser i terrenget rundt og i skogkanten når jeg kjører på veiene

**Comment by OlaHaldor** [comment]
Kan du ta opp video av at det skjer?

**Comment by Tractorgay** [comment]
Med vennlig hilsenUlf EriksenTlf:95288250
-------- Opprinnelig melding --------Fra: OlaHaldor ***@***.***> Dato: 26.08.2022  09:23  (GMT+01:00) Til: MapsOfNorway/rennebugs ***@***.***> Ko: Tractorgay ***@***.***>, Author ***@***.***> Emne: Re: [MapsOfNorway/rennebugs] Svart flimring  (Issue #120) 
Kan du ta opp video av at det skjer?

**Comment by OlaHaldor** [comment]
Ser ingen respons på dette. Lukker.
