### ISSUE TITLE
Black cliff and strange log error

### ISSUE THREAD

**Issue by Makarovmw2** [MapsOfNorway/rennebugs#121]
![Screenshot_287](https://user-images.githubusercontent.com/112247964/187024768-af15b933-9881-415f-8490-4d31c83eb4e6.png)
![Screenshot_288](https://user-images.githubusercontent.com/112247964/187024788-f41c2367-8424-4b16-bc29-4532d766af4e.png)

Version of the map 1.0.0.1, i found this bug while driving and opening the log i see the error on the screenshot, and looking in the log.txt i found other problem, down there is the log file

[log.txt](https://github.com/MapsOfNorway/rennebugs/files/9437688/log.txt)

**Comment by OlaHaldor** [comment]
Third or fourth time I see this reported. Don't know why. But the fact you actually get a HLSL error is interesting.
Does it happen if you lower your graphics settings too ?

**Comment by Makarovmw2** [comment]
so i try some setting and now it's all normal, no more error and no more black cliff. i change the directx back to 12 because on one other map if i don't change that value to 11 all the decal inside all tractor became blurry

**Comment by OlaHaldor** [comment]
Was there any change to this after the latest patch which came today?

**Comment by OlaHaldor** [comment]
Closing this as there's no new info.
