### ISSUE TITLE
Cant finish missions.

### ISSUE THREAD

**Issue by hardcor3crash** [MapsOfNorway/rennebugs#123]
Some Contract missions cant be finished. They get stuck at something between 86% and 99%. We had issues on Field 9 24 74 120. We play on Dedi MP Server

**Comment by OlaHaldor** [comment]
I see there's multiple reports about contracts and not able to finish, or warnings that "you don't have access to this field". 
So far I'm in the dark sadly. I don't know why this happens. Technically, everything is good.

I wonder if this is one of the downsides with huge maps.

Until Giants gives a comment about this, I'm in the dark about where to start looking.

**Comment by hardcor3crash** [comment]
Maybe its due to the bad precision while harvesting on 4x/8x maps in FS22.

**Comment by OlaHaldor** [comment]
That may be the problem.
Do you play on other large maps? If so, do you have the same issue there?

**Comment by OlaHaldor** [comment]
No news for a long time. Closing the ticket with no obvious solution.

**Comment by RTHauke** [comment]
This seems to be related to the "expectedLiters" amount for the missions being too high.  I've attached the missions.xml file from a save where I've turned in all harvested product for a mission on field 39 but it will not complete.  The file indicates:
`<harvest sellPointPlaceableId="14" unloadingStationIndex="1" expectedLiters="24493.728516" depositedLiters="20337.511719"/>`
[missions_xml.txt](https://github.com/MapsOfNorway/rennebugs/files/10027270/missions_xml.txt)

**Comment by RTHauke** [comment]
I've had this issue on several contracts.  It seems to be related to the "expectedLiters" amount for the missions being too high. I've attached the missions.xml file from a save where I've turned in all harvested product for a mission on field 39 but it will not complete. The file indicates:
`<harvest sellPointPlaceableId="14" unloadingStationIndex="1" expectedLiters="24493.728516" depositedLiters="20337.511719"/>`

All of my issues involved contracts for harvesting Sorghum using contracted equipment or my own (fully repaired or new) equipment.
 
[missions_xml.txt](https://github.com/MapsOfNorway/rennebugs/files/10027332/missions_xml.txt)

**Comment by hansnqyr** [comment]
To build on @RTHauke comment, I had this happen on my very first contract, and looked into it a bit deeper:
**mission**: field 45, harvest oats
**expected** (ref missions.xml): **~45670 liters**
**achieved** (ref missions.xml): **~40187 liters** (this was from a thorough harvest imho)
**field size**, according to giants editor field size script: **4.7 hectares**
**expected yield**, (ref https://farmingsimulator.app/en/crop-yield-calculator-bonus-fs22): **53580 liters**

The mission generation seems reasonable given the expected yield, so the issue probably is with how the field size is being calculated, or maybe the harvestable area within the field being too small? Is 4.7 hectares accurate for field 45?
