### ISSUE TITLE
Cows not producing milk

### ISSUE THREAD

**Issue by GetRexed** [MapsOfNorway/rennebugs#124]
Hello. First off, Outstanding map! I'm really enjoying it so far.  Now, on to the cows...I've had milking cows in Bruholt for several months and they are producing slurry and manure but not milk. I have all 3 types of food for 100% effectiveness as well as straw. Productivity and health have both been at 100% for a while. I've included a screenshot for reference. Thank you.  (Version 1.0.0.1 map/pack)

![image](https://user-images.githubusercontent.com/113269248/189506762-3213139f-7136-4c60-8d6f-a7c2522aa620.png)

**Comment by DrewCZ** [comment]
Hi, these Holsteiners on the printscreen are in PUBERTY stage at 16%. They cannot produce milk. Check ingame help.

**Comment by OlaHaldor** [comment]
Case closed

**Comment by GetRexed** [comment]
My apologies...first time with cows and didn't know they had to be 12 months before producing milk. Thank you.
