### ISSUE TITLE
No sell point for olive oil.

### ISSUE THREAD

**Issue by GetRexed** [MapsOfNorway/rennebugs#125]
Hello again. Lesser issue this time then the milkless cow. I see the grain mill also produces olive oil but I don't see olive oil in the sell list at any location. Thak you.  (Version 1.0.0.1 map/pack)

**Comment by OlaHaldor** [comment]
Oops! Should be at the grocery store. I'll check it.

**Comment by OlaHaldor** [comment]
I found the issue, and it's fixed. Olive oil will be visible in the price list in the coming update.
