### ISSUE TITLE
some land not buyable. was this intentional? 

### ISSUE THREAD

**Issue by GetRexed** [MapsOfNorway/rennebugs#127]
Hello. The piece of land between 43, 49 and 50 is not buyable. Noy sure if this was an oversight or intentional. I have no idea how to edit the files to make it buyable lol. Thank you. 

![image](https://user-images.githubusercontent.com/113269248/189989225-9bbdda76-c1b1-4d43-b05a-a68ca972a495.png)

**Comment by OlaHaldor** [comment]
Noted. Will fix this.

**Comment by OlaHaldor** [comment]
Done
