### ISSUE TITLE
Cant spred slurry

### ISSUE THREAD

**Issue by THEBACONBEAST554** [MapsOfNorway/rennebugs#130]
its not working

**Comment by OlaHaldor** [comment]
You will need to tell me a bit more than that. I can't fix what I don't know anything about.

Where does it happen?
Is the slurry tank a mod?
Screenshot or video of the case would be most helpful.

**Comment by OlaHaldor** [comment]
Have not heard back for a while. Closing the ticket.
Feel free to re open the ticket if you have more information to give.
