### ISSUE TITLE
Placables 

### ISSUE THREAD

**Issue by KapteinT** [MapsOfNorway/rennebugs#14]
![image](https://user-images.githubusercontent.com/74627757/179202651-36190d7a-8f17-4e25-aa7c-ac20c084e1bc.png)
![image](https://user-images.githubusercontent.com/74627757/179203475-2351befb-006b-4082-870d-f17660b41fad.png)

Fjøs Plaseres ikke riktig på Flatmark

https://youtu.be/6-z3wi8cU2Y

**Comment by OlaHaldor** [comment]
This is a little more time consuming. Will get back to it once the 'easy fixes' are done.

**Comment by OlaHaldor** [comment]
Fixed! :)
