### ISSUE TITLE
Game freezing collision error ?

### ISSUE THREAD

**Issue by JukeStuff** [MapsOfNorway/rennebugs#146]
![image](https://user-images.githubusercontent.com/113805245/210128879-23667ef2-8f60-4b07-bddd-74fb0a442324.png)
Rennebu 1.0.0.1
Buildings Of Norway 1.0.1.0
![image (1)](https://user-images.githubusercontent.com/113805245/210129000-56c531c5-2353-4cf7-a5e4-adea714f7924.png)
Somewhere in the Right side of field 1 (Marked in second picture) there is some kind of collision error i think. Multiple time with combines and tractors when driving around/ having a worker around that area the machine has "teleported" to null-null making the game run at 1 fps.

**Comment by JukeStuff** [comment]
Just happened again and this is what the log says 
![image](https://user-images.githubusercontent.com/113805245/210129377-ddebb12d-7227-4458-9142-616d00193743.png)
http://modsfile.com/jczbdz9vpvi0/log.rar.html

**Comment by OlaHaldor** [comment]
That's new to me, thanks for reporting. Will have a look.

**Comment by OlaHaldor** [comment]
Can't say I've found anything in the area or have any idea what the error message even means.
