### ISSUE TITLE
On dedicated server

### ISSUE THREAD

**Issue by SwedenForest** [MapsOfNorway/rennebugs#148]
I got these issues.

GDM file 'mapRennebu/data/densityMap_fruits.gdm' is too big. Size 46.64 MB (max. 18.00 MB)
PNG texture file 'mapRennebu/data/mapRennebu_dem.png' is too big. Size 15.57 MB (max. 4.00 MB)
Space character not recommended in filename: 'mapRennebu/import/textures/roadbarriers/road barrier trim sheet_diffuse.dds'
Space character not recommended in filename: 'mapRennebu/import/textures/roadbarriers/road barrier trim sheet_normal.dds'
Space character not recommended in filename: 'mapRennebu/import/textures/roadbarriers/road barrier trim sheet_specular.dds'
I3D file 'mapRennebu/rennebu.i3d.terrain.lod.type.cache' is too big. Size 32.00 MB (max. 10.00 MB)
I3D file 'mapRennebu/rennebu.i3d.terrain.nmap.cache' is too big. Size 32.00 MB (max. 10.00 MB)
I3D file 'mapRennebu/terrain.lod.type.cache' is too big. Size 32.00 MB (max. 10.00 MB)

**Comment by OlaHaldor** [comment]
These warnings are not unusual. The map is larger and more demanding than what the game engine officially support. 

The file names are already fixed and part of the coming update. Closing the ticket.  :)
