### ISSUE TITLE
Some houses show up as white see through placeholders

### ISSUE THREAD

**Issue by Bryserker** [MapsOfNorway/rennebugs#152]
Edited: Changed title from most -> some. It's definitely not most, it just felt that way at the spawn location.

Hi,

When I start a new game on the Rennebu map, some of the houses on the map show up as placeholders, an example right at the spawn location:

![image](https://user-images.githubusercontent.com/39168894/226103408-1a804a70-bc6b-4be1-b84b-32ea54f064fb.png)

I have tried/tested the following:
* Download Rennebu + Buildings of Norway through farming-simulator.com;
* Download Rennebu + Buildings of Norway through the in-game mod hub;
* Verify all FS22 files through Steam;
* Removed all other mods to check for conflicts.
* Verified I can place 

None of these solved the issue. 

This versions are Rennebu v1.0.2.0 / Buildings of Norway v1.0.2.1.

The thing that stood out to me is that not all buildings are this way and that I also can't find certain buildings in the construction menu. For example, the 'Oppstuggu Cow Barn' is a placeholder and I also can't place it through the construction menu. However, the 'Bergtun Cow Barn' does show up normally on the map and is also available through the construction menu.

I tried finding a place to download Buildings of Norway v1.0.2.0 to compare, but couldn't find a site that offered it for download.

**Comment by vjludovico** [comment]
Having the same issues and tried the same fixes. I did try to change the graphical settings and deleting the shader cache to no avail. I have verified the missing buildings that show as white and that can't be constructed are listed in the Buildings of Norway file (at least the XMLs are) Also having some serious issues with the chainsaw alignment but that has to be an entirely different issue.

**Comment by lysinelai** [comment]
They probably are placeholder models to begin with, opened some of the models in the editor and they are just like that in the editor.

**Comment by OlaHaldor** [comment]
These are exactly what you say, place holders. They're there to indicate there will be new buildings in future updates, to prevent you from building on the farm and in the future get a surprise when you update the building pack.

If you buy the farm and sell the buildings to make your own version, you're of course free to do that. 

Closing this one as it's not an issue.
