### ISSUE TITLE
A couple of Errors and Warnings in the FS22 log file

### ISSUE THREAD

**Issue by 1972Patrick** [MapsOfNorway/rennebugs#157]
It's a wonderful atmospheric Map and i love to play on it, but it has a couple of Errors and Warnings in the FS22 log file.
To sort things out, i started a new savegame with only the Map and the Bildings Pack in it.

I send you the Log file to your information:

[log.txt](https://github.com/MapsOfNorway/rennebugs/files/11087833/log.txt)

**Comment by OlaHaldor** [comment]
The errors have been sorted, will be part of a future update. :) 
The warnings  aboout l10n entries have also been sorted.
