### ISSUE TITLE
White ghost like buildings

### ISSUE THREAD

**Issue by Anthrophaxiom** [MapsOfNorway/rennebugs#159]
The map has a lot of white ghosted buildings, they're collidable (you can drive on ramps etc) but the texture is missing completely.
Any ETA on when this could get solved?

Flott map btw!

**Comment by OlaHaldor** [comment]
This is on purpose. If I didn't place temporary buildings, you would have to start the savegame from scratch again to get the buildings.

I placed them so you know where they will come in the future, so you can decide whether to remove them or to let them be.
It would be an unpleasant surprise to build your farm and when there's an update in the future, the buildings would appear inside your own farm. :) 

I also hate the thought of forcing players to restart their savegames.
