### ISSUE TITLE
Floating fences and random landscaping

### ISSUE THREAD

**Issue by Anthrophaxiom** [MapsOfNorway/rennebugs#160]
Hei. Kameraten min opplever at gjerder plutselig flyter og at terrain randomly modifiserer seg. Dvs. store gaps i bakken og at bakken plutselig forhøyer seg og skaper høye vegger uten collision som han kan kjøre gjennom. Hvis han sletter (1) del av gjerdet, så "detter" det ned igjen til normal høyde. Bakken forblir slik. Det som er rart er at jeg ikke ser dette på min side, så når jeg er på hans gård og ser meg rundt så er alt tilsynelatende normalt. Vært borti dette eller har en formening om hva det kan være? Begynner å lure på om det er en mod, men med 389 mods currently installed så blir det som å finne nåla i høystakken. Se bilder nedenfor.

![Floating](https://user-images.githubusercontent.com/131037110/236017419-f1bd2641-af2e-472c-8cd4-8882b6d55ee1.png)

![fences](https://user-images.githubusercontent.com/131037110/236017483-6b172311-d938-418d-9bc2-3dca251fc488.png)

**Comment by Anthrophaxiom** [comment]
Har for øvrig ikke noe å si hvor på kartet det er, skjer uansett hvor han har gård. Og på hans skjerm, skjer dette på min gård også, enda jeg ikke ser det på min egen gård selv. Er på nyeste versjon av kartet

**Comment by OlaHaldor** [comment]
Beklager sen respons! 
har dere dette problemet enda?
Jeg har ikke opplevd dette selv.
Dere spiller multiplayer antar jeg - får dere noe feilmeldinger på serveren?

**Comment by Anthrophaxiom** [comment]
> Beklager sen respons! 
> 
> har dere dette problemet enda?
> 
> Jeg har ikke opplevd dette selv.
> 
> Dere spiller multiplayer antar jeg - får dere noe feilmeldinger på serveren?

Hei! Null stress. Vi bemerket oss for noen uker siden at problemet fulgte over til et annet map, så da konkluderte vi raskt med at det ikke kunne være noe med Rennebu mappet. Har filtrert i mod mappen tilbake til rundt tidspunktet jeg rapporterte dette til deg, og slettet en del mods fra det tidspunktet så får vi se. Men da er det uten tvil mod relatert :)
