### ISSUE TITLE
Stutters and lag Multiplayer.

### ISSUE THREAD

**Issue by mountainboomer** [MapsOfNorway/rennebugs#163]
We are running into a lot of server lag and stutters in the area around farms 110 down through 133.  Especially around 112, 119, Noticed on the other side of the river around the hwy 700 marker.

Love the map!  

North bridge is quite narrow.  Not sure if it intended for cars or tractors.  My pickup truck was able to cross.  Looks more like a foot or people bridge.  Could be 2x as wide or more.

**Comment by OlaHaldor** [comment]
The lag is only on multiplayer? Or on single player as well?
There's a ton of trees on the map. And the more you own, the more resources are required to run the map.
It's sort of a double (possible) problem; either your pc is not powerful enough for the settings you use, or the server isn't powerful enough. I've heard 16GB ram is recommended.

the bridge at the north end is made just as it is irl. It can barely take cars. Or very small tractors and equipment.
