### ISSUE TITLE
Tomter 

### ISSUE THREAD

**Issue by KapteinT** [MapsOfNorway/rennebugs#17]
![image](https://user-images.githubusercontent.com/74627757/179222398-cfcafef9-edf0-427d-acec-578946ab0aed.png)
Kan ikke kjøpe Hele kartet også Landscaping fungerer dårlig når du ikke kan landscape på grensene mellom tomter også mellom eiendom og vei, siden det ikke er kjøpbart.

**Comment by OlaHaldor** [comment]
Om du skaffer Easy Dev Tools kan du kjøpe kjøpe alt.

Om det er spesifikke punkter i kartet du mener det er nyttig å sculpte på tvers av grenser som ikke fungerer er det til stor hjelp om du peker de ut så jeg kan se på det.
