### ISSUE TITLE
Animal Dealer delivery

### ISSUE THREAD

**Issue by zakhodgsonamauk** [MapsOfNorway/rennebugs#173]
Through the transport mission mod, it's asked that I deliver to the animal dealer. However, it seems the animal dealer does not have a delivery location, to unload to, or if it does, it is inside the black shed that cannot be opened.

Lovely map by the way!

**Comment by OlaHaldor** [comment]
What were you supposed to deliver? 
There is a zone (though unmarked) right in front of the sliding doors. They cannot be opened (per now, there is no proper interior, so it would look ugly). 

Try delivery at the ramp, just in front of it.
