### ISSUE TITLE
Spawned planks, beams ect. not sellable at carpentry

### ISSUE THREAD

**Issue by MariusTro** [MapsOfNorway/rennebugs#174]
I own sawmill and carpentry. First time trying this and I have spawned all my pallets of beams, planks ect and transported them all they way to the carpentry. When I get there I cannot do anything with them. I tried storing wood but that only apply to logs. So basically I cannot do anything with the spawned products from my own production?

**Comment by OlaHaldor** [comment]
You should be able to sell your products there. Where exactly at the carpentry are you trying to unload? 
The products should automatically unload when you're in the zone.

**Comment by MariusTro** [comment]
Hi. Skal sjå om eg får tatt opp ein video snutt på mobilen idag. Er mulig
ein mod konflikt men er liksom ingenting anna som virker feil.

Marius

søn. 30. jul. 2023, 23:23 skrev OlaHaldor ***@***.***>:

**Comment by MariusTro** [comment]
Hei

Her er ein link til ein liten video snutt.

https://photos.app.goo.gl/HAiyompXoR9rUMLZ8

Her er mine mods. Ser du noko som kan laga konflikt kanskje?
[image: 20230804164433_1.jpg][image: 20230804164440_1.jpg][image:
20230804164447_1.jpg][image: 20230804164452_1.jpg]

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

man. 31. juli 2023 kl. 07:52 skrev Marius Trones ***@***.***>:

**Comment by OlaHaldor** [comment]
Hei, jeg ser ikke bildene av modsene du la inn.

Jeg foreslår at du prøver et nytt savegame med kun buildings of norway og eventuelt easy dev controls (og platinum dlc om du har) for å spawne noe planker og tømmer, og ser hva som skjer.

**Comment by MariusTro** [comment]
Hei

Bildene låg inne i mailen og ikkje inne i linken.

Eg skal prøve det ja. Men det hadde vært kult om du kunne kanskje gi meg
noen pointere om kva mod som evt. kunne ha vært i konflikt. Det må vel være
ein mod som bruker samme filer som funksjonen din for salg?

[image: 20230804164433_1.jpg]
[image: 20230804164440_1.jpg]
[image: 20230804164447_1.jpg]
[image: 20230804164452_1.jpg]


Mvh Marius Trones

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_2161363474142263535_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

fre. 4. aug. 2023 kl. 18:43 skrev OlaHaldor ***@***.***>:

**Comment by OlaHaldor** [comment]
Jeg får fremdeles ikke sett bildene.
Du kan copy-paste bildet direkte i svaret, så lastes det opp til github.

Jeg har ikke gjort noe ekstraordinært med snekkeriet. Det er helt standard funksjoner i Farming Sim.

Hvis det er en mod konflikt må feilen være på andre kart hvor det er snekkeri også.

**Comment by MariusTro** [comment]
Eg har fjernet alle andre kart og gått igjennom moddene min. Eg finner
seriøst ikkje ut av dette.

Her er ein link med ingame bilde av alle moddene mine. Ser du noe som kan
muligens være konflikt?

https://photos.app.goo.gl/VXHP6jrrYPU2dScm6

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

lør. 5. aug. 2023 kl. 16:40 skrev OlaHaldor ***@***.***>:

**Comment by OlaHaldor** [comment]
Kan du sende savegamet ?

**Comment by MariusTro** [comment]
Er det ein enkel måte å gjøre det på? Finner berre mapper som heter
savegame og den som blei oppdatert sist er 120mb komprimert som zip.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

søn. 6. aug. 2023 kl. 10:49 skrev OlaHaldor ***@***.***>:

**Comment by MariusTro** [comment]
link:
https://drive.google.com/file/d/17zCuX_nmtEfLN7nZMVDSK011-DqJckGN/view?usp=drive_link

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

søn. 6. aug. 2023 kl. 12:14 skrev Marius Trones ***@***.***>:

**Comment by OlaHaldor** [comment]
Kanskje production revamp modden klusser til? Eller en av de pallets moddene? Jeg greier ikke se noe annet.

Legger ved video som viser at jeg ikke har noe problem med å selge.
https://github.com/MapsOfNorway/rennebugs/assets/60529378/2e482541-22d3-455f-a9b8-76676f9146eb

**Comment by MariusTro** [comment]
Hei

Då har eg testet og testet. Eg har fjernet alle mods som har med produksjon
og kjøp / salg av varer. Er egentlig berre guided steering, course play,
traktorer og utstyr igjen. Så då gir eg opp tenker eg.


Hadde vært kjekt med eit verktøy for å teste konflikter i fs modder. Finnes
noe slikt eller?

Mvh Marius

man. 7. aug. 2023 kl. 20:46 skrev OlaHaldor ***@***.***>:

**Comment by MariusTro** [comment]
Fant den faktisk. Det var i gruppa med modder eg aldri hadde trodd skulle
være grunnen.

Modden heter "Increased Unloading Times". Eg trudde at den modden kun
virket på tømming av vogner og ikkje paller med planker.

Du kan teste dette nå og evt. legge den til ikke kompatibel.

Mvh Marius

søn. 20. aug. 2023 kl. 09:24 skrev Marius Trones ***@***.***>:

**Comment by OlaHaldor** [comment]
Supert, takk for tilbakemelding :)
