### ISSUE TITLE
Building 

### ISSUE THREAD

**Issue by DarkGriffin62** [MapsOfNorway/rennebugs#177]
I have some buildings that appear as white shadows like ghost buildings, some have the 2x4 framing visible

**Comment by KindCoder-no** [comment]
I think that is because he has not finished the building yet, but is using a placeholder, so the map wont break on a later update if you place buildings there yourself

**Comment by KindCoder-no** [comment]
See related issue: https://github.com/MapsOfNorway/rennebugs/issues/159
