### ISSUE TITLE
Tomter og landscaping

### ISSUE THREAD

**Issue by KapteinT** [MapsOfNorway/rennebugs#18]
![image](https://user-images.githubusercontent.com/74627757/179222398-cfcafef9-edf0-427d-acec-578946ab0aed.png)
Kan ikke kjøpe Hele kartet også Landscaping fungerer dårlig når du ikke kan landscape på grensene mellom tomter også mellom eiendom og vei, siden det ikke er kjøpbart.

**Comment by OlaHaldor** [comment]
Er Det et spesifikt område du skulle ha kjøpt?

**Comment by BeardsViking** [comment]
Det er også problemer med å kunne landskape på noen av gårdene. Får ikke flatet ut terenget

**Comment by OlaHaldor** [comment]
Det kan ha noe med at der du ønsker å endre landskapet er for nært bygninger. Det samme ville skjedd med standard bygninger også vil jeg tro.

det finnes en mod som lar deg sculpte landskapet uansett. Tror den heter noe sånt som Sculpt Anywhere eller noe i den dur
