### ISSUE TITLE
Gress som kommer gjennom ting.

### ISSUE THREAD

**Issue by NorthmanLive** [MapsOfNorway/rennebugs#19]
Ser flere plasser at høyt gress kommer gjennom ting og det er gress på innsiden av enkelte byggninger. Her er et bilde fra hvordan det ser ut i en conteiner som er ved startplassen. Er bagateller og regner med det blir fikset etterhvert eller kanskje ikke :)

![image](https://user-images.githubusercontent.com/49675977/179225930-eda3bb70-187b-4121-8e22-df1754876419.png)

**Comment by OlaHaldor** [comment]
Ikke en stor issue - det kommer andre bygg her med tiden. :)
