### ISSUE TITLE
AI traffic is stuck

### ISSUE THREAD

**Issue by TrainzmanUK** [MapsOfNorway/rennebugs#2]
![image](https://user-images.githubusercontent.com/47663166/179055192-8c6ac8e4-279e-4bf8-839d-5057a2f77e0d.png)
Once a vehicle has reached this point on the map it stops and all traffic behind back up :(

**Comment by TrainzmanUK** [comment]
red pickup is me

**Comment by TrainzmanUK** [comment]
![image](https://user-images.githubusercontent.com/47663166/179055859-3ca8f318-895d-4796-8639-528fab438b7e.png)

**Comment by dbump** [comment]
If you have AutoDrive installed, and let it generate a route based on the AI traffic splines, the route here dead ends exactly where the traffic stops.  Usually I see the AD routes loop back (sometimes off the edge of the map) but these appear to simply stop, which I believe is why the AI traffic also stops where it does.

**Comment by TrainzmanUK** [comment]
Hmm, that makes sense, I did get sent a route for this map, so maybe it was a localised AI traffic one?

**Comment by dbump** [comment]
I only mentioned AutoDrive because it shows an interpretation of the map's own traffic spline (though the AD route itself does not influence the AI traffic--it's optionally auto created based on it though).  I have not looked at the splines in Giants Editor to confirm that they dead-end.

**Comment by OlaHaldor** [comment]
I will have a closer look at this first thing when I'm home :) interesting that AD dead ends at the intersection (?). That's a good indicator of where to look.

**Comment by TrainzmanUK** [comment]
> I will have a closer look at this first thing when I'm home :) interesting that AD dead ends at the intersection (?). That's a good indicator of where to look.

Thanks, as at the moment using AD, its a game stopper :(

**Comment by KindCoder-no** [comment]
![proShot_2022-07-27_22-23-44](https://user-images.githubusercontent.com/40148297/181365648-1273eee6-e24f-4807-9fe5-dab36a91ca8d.png)
Same issue
