### ISSUE TITLE
Cars stuck

### ISSUE THREAD

**Issue by inocent16** [MapsOfNorway/rennebugs#21]
![grafik](https://user-images.githubusercontent.com/109361318/179243381-4760f902-6438-40c5-ae5f-2e7dfae3f543.png)

**Comment by jufcar** [comment]
I noticed somthing similar, while driving past them in tractor. It looks like the trigger, that checks for collisions is to big.

**Comment by TrainzmanUK** [comment]
see my original post
https://github.com/MapsOfNorway/rennebugs/issues/2

**Comment by konk1980** [comment]
as soon as you create courses with autodrive automatically, there is a gap between the splines:
![grafik](https://user-images.githubusercontent.com/78075165/179345826-667ef152-44f2-4bca-bf7c-7ab38b7453cd.png)

**Comment by OlaHaldor** [comment]
Solved
