### ISSUE TITLE
Horse paddock does not allow tipping of oats?

### ISSUE THREAD

**Issue by TrainzmanUK** [MapsOfNorway/rennebugs#22]
Tried various ways of tipping oats using many different methods and its not accepting them?

**Comment by OlaHaldor** [comment]
Should take big bags of oat inside. I can adjust this so you can silo with a trailer on the outside.

**Comment by RaffiM** [comment]
> Tried various ways of tipping oats using many different methods and its not accepting them?
It worked for me after trying around a little bit. Just hover the oat big bag close to and over the tipping symbol. That worked for me ...

**Comment by TrainzmanUK** [comment]
Thanks, this can be marked as a solution :)

**Comment by TrainzmanUK** [comment]
Hmm, I had a schoolboy error moment, I filled up the horses with hay and thats why I could not apply oats to the feed area it seems?

**Comment by OlaHaldor** [comment]
Would you like me to make this more clear somehow?

**Comment by TrainzmanUK** [comment]
Just increase the size of the tipping point so its both side of the fence would help, if you have done that, then thats fine with me :)

**Comment by TrainzmanUK** [comment]
Works fine inside the field?

![image](https://user-images.githubusercontent.com/47663166/179986431-8713a785-19a0-4b6d-9634-fd65d9e32bd1.png)

**Comment by OlaHaldor** [comment]
Trigger is extended to also reach just outside the fence.
