### ISSUE TITLE
sellpoint grainmill  ##closed

### ISSUE THREAD

**Issue by konk1980** [MapsOfNorway/rennebugs#27]
cannot buy solid fertilizer at sellpoint grainmill

**Comment by OlaHaldor** [comment]
Please supply a screenshot

**Comment by konk1980** [comment]
![grafik](https://user-images.githubusercontent.com/78075165/179352113-4682c982-41d3-4de6-822b-078fc98c1ddc.png)

**Comment by OlaHaldor** [comment]
Try driving on the ramp next to the big bags :)

**Comment by konk1980** [comment]
no: 
![grafik](https://user-images.githubusercontent.com/78075165/179357957-67279a5e-6315-44ba-9094-4ea758a7c2a8.png)

**Comment by OlaHaldor** [comment]
Open the cover :)

**Comment by konk1980** [comment]
it opens autmatically as soon as there is something to fill ;-) not at that spot...

**Comment by konk1980** [comment]
layer 8...

##closed##
