### ISSUE TITLE
NPC trafikken stopper ved veikryss Feldt 62

### ISSUE THREAD

**Issue by Wowfaktor** [MapsOfNorway/rennebugs#28]
NPC trafikken stopper ved veikryss Feldt 62

**Comment by NdMoreSpd** [comment]
https://github.com/MapsOfNorway/rennebugs/issues/2#issue-1305145090

**Comment by Smurfenstein** [comment]
Maybe that right turn where traffic comes from bridge is too steep?

**Comment by OlaHaldor** [comment]
I've deleted the turn for now.
