### ISSUE TITLE
cant sell at joker

### ISSUE THREAD

**Issue by lukasvri** [MapsOfNorway/rennebugs#30]
cant sell at joker 
![image](https://user-images.githubusercontent.com/22594782/179362255-aeee64f5-7f53-443b-bb61-9546cbd0a250.png)

**Comment by lukasvri** [comment]
i cant sell flour anny were

**Comment by OlaHaldor** [comment]
Should work, never seen the issue before.
Sure you're inside the trigger area?

can you sell other things?

**Comment by lukasvri** [comment]
i can sell bales

**Comment by OlaHaldor** [comment]
Huh that's strange. Will have a look in a couple weeks when I'm home.

**Comment by TrainzmanUK** [comment]
Strange indded as I just took some there and it sold OK?
![image](https://user-images.githubusercontent.com/47663166/179410255-7b5afcf3-a05d-4e2f-9484-ccf085677db5.png)

**Comment by lukasvri** [comment]
started a new save game and i work now so was something wrong with the save

**Comment by OlaHaldor** [comment]
If you have the old save it could be interesting to experience it first hand and have a closer look

**Comment by lukasvri** [comment]
sorry i deleted it

**Comment by lukasvri** [comment]
i think its this
http://www.mediafire.com/file/imntd9ck2rdfo4q/savegame3.zip

**Comment by Jos-B** [comment]
Trigger area height could be the issue.

![joker-sellarea](https://user-images.githubusercontent.com/228633/179553801-98de8d1e-1399-4f7c-8e35-701657381c2e.png)

**Comment by MariusTro** [comment]
I got the same issue. Can not sell the wool I have produced in the sheep barn. I tried moving the pallet around the area but it did not sell.

**Comment by OlaHaldor** [comment]
Increased size and height.
