### ISSUE TITLE
Ingen triggere på placeble fjøsene. 

### ISSUE THREAD

**Issue by Skauningen** [MapsOfNorway/rennebugs#32]
Verken trigger for dørene, fôring, uttak av gjødsel og dyre trigerne er tilstedet. Det vises når du skal til å sette det ut, men når du plasserer det ned/kjøper så forsvinner det. 
Det går heller ikke å selge bygninger man har satt ut
![fsScreen_2022_07_16_22_43_05](https://user-images.githubusercontent.com/109438810/179371774-e231bbc9-336a-42c8-be3d-feaabe662251.png)
![fsScreen_2022_07_16_22_43_49](https://user-images.githubusercontent.com/109438810/179371775-02e121fa-8950-4d0e-bd13-ac6813914cd9.png)

**Comment by OlaHaldor** [comment]
Sjekk innstillingene dine. Du har mest sannsynlig slått av å vise disse ikonene.

**Comment by Skauningen** [comment]
Va de æ å trudd, men dæm e på. Fungere på allt snna ennj på tilæggsmoddn
(bygningan). Gårhusa har heller ikke nå.
Kun søu å ku fjøset som står fra før funke som normalt.
Nå tilægsmod en må ha ellj?

MoenGård ved Snorre Moe
Snorre Moe
Tlf: 40612326
Nerjåren 114
7357 Skaun
Org nr: 923 816 674

søn. 17. jul. 2022, 02:26 skrev OlaHaldor ***@***.***>:

**Comment by OlaHaldor** [comment]
Hvis du ser det på gården man starter med men ingen andre; har du kjøpt de andre gårdene?

**Comment by OlaHaldor** [comment]
Ut fra det jeg ser i minimap eier du ikke jorda der bygningene står

**Comment by Skauningen** [comment]
Aha ja stæmt bra de ja. Avanserte greier farming hi verte sea en bynt i
2009. Skylle på ferimodus. Takk no👍🏻. Nå tå de likast karta en hi verre
borti på fler år no👌🏻 stå på

MoenGård ved Snorre Moe
Snorre Moe
Tlf: 40612326
Nerjåren 114
7357 Skaun
Org nr: 923 816 674

søn. 17. jul. 2022, 02:36 skrev OlaHaldor ***@***.***>:

**Comment by OlaHaldor** [comment]
Godt! :) god ferie! :)
