### ISSUE TITLE
Invisible Trees (Between Field 9 and 12)

### ISSUE THREAD

**Issue by Knuspexs** [MapsOfNorway/rennebugs#34]
![Field 12 - Ghost Tree 01](https://user-images.githubusercontent.com/96056724/179388636-6f0f0dfb-db88-463c-9a63-c587fd4fb5ee.png)
![Field 12 - Ghost Tree 02](https://user-images.githubusercontent.com/96056724/179388643-3a608f2d-1233-40d6-9e37-769b53f1915a.png)

**Comment by OlaHaldor** [comment]
Oh boy! Well spotted. I'll sort it out asap when I'm back from vacation
