### ISSUE TITLE
will not save (multiplayer) and savegame freezes(multiplayer) 

### ISSUE THREAD

**Issue by fredbens** [MapsOfNorway/rennebugs#35]
have to use multiple attempts before the game will save and multiple failures of saving. 

The game froze when a friend of mine joined and it worked fine for him but not me.

**Comment by OlaHaldor** [comment]
This sounds more like a limitation of hardware than the map being the problem.

The map requires more features than other, smaller maps. So what can cause this, I don't know. 

I can bring the issue to a contact at Giants and hear what he has to say.
