### ISSUE TITLE
Texture på precision farming kartet

### ISSUE THREAD

**Issue by BeardsViking** [MapsOfNorway/rennebugs#36]
Texturen på precision farming kartet har veldig lav oppløsning i forhold til andre kart.

**Comment by OlaHaldor** [comment]
Det kan jeg dessverre ikke gjøre noe med. Oppløsningen kan ikke økes, og er en teknisk begrensning i spillmotoren.

**Comment by BeardsViking** [comment]
Er det grunnet størrelsen på kartet ? For de karta jeg har spilt på før har vert høyere oppløsning, men mindre map

**Comment by OlaHaldor** [comment]
Stemmer.
Precision farming bildefilen kan kun være 1024x1024, men ideelt burde den vært 4096x4096.
Med mindre Giants gjør en endring og tillater høyere oppløsning er det ingenting jeg kan gjøre noe med.
