### ISSUE TITLE
Wo Verkauft man Raps

### ISSUE THREAD

**Issue by Granatenjoe** [MapsOfNorway/rennebugs#38]
Wo Verkauft man Raps, die angegebene Getreide mühle die es Ingame game gibt. Die nimmt kein Raps an

**Comment by OlaHaldor** [comment]
It's a mistake on my behalf.
The grain mill irl does not accept canola, and in FS22 canola is used to make oil as far as I know.

Seeing multiple reports about this I'm considering the mill also act as an oil factory for sunflower and canola.

I will get going with that when I'm back from vacation in 2 weeks

**Comment by OlaHaldor** [comment]
I have a solution. Will be fixed in a future update.
