### ISSUE TITLE
Worker driving issue

### ISSUE THREAD

**Issue by Game5Plays** [MapsOfNorway/rennebugs#39]
The worker takes a dumb route when passing the grain mill

**Comment by OlaHaldor** [comment]
Please provide a screenshot. Draw on if it can help point out what happens. Or a video.

**Comment by Game5Plays** [comment]
At the moment it trives thru the red path, when i beleve it shoud drive thru the green path

![Skjermbilde 2022-07-18 195320](https://user-images.githubusercontent.com/109349693/179572738-f3fb2977-9f36-4318-aeca-d5259b66441f.png)

**Comment by OlaHaldor** [comment]
THanks! 
That's a first. Will look into it.

**Comment by OlaHaldor** [comment]
Fixed
