### ISSUE TITLE
Kan ikke selge bygninger

### ISSUE THREAD

**Issue by kandk1** [MapsOfNorway/rennebugs#4]
Hei.
Jeg kom til å plassere et fjøs på feil sted og oppdaget at det ikke kunne selges igjen. Prøvde så med flere bygninger og hus fra Buildings of Norway-pakken men det er samme problem med alle jeg prøvde. Når jeg klikker på "riv"-funksjonen i menyen og fører musepekeren over bygningen jeg ønsker å fjerne, skjer det ingenting, dvs bygningen dekkes ikke med den "filmen" som vanligvis dukker opp når man holder pekeren over. Testet samtidig med et basegame-hus og det funket som normalt å fjerne.

Fantastisk map og det var stor stas da det kom ut. Har ventet i spenning på dette mappet et par år. Tusen takk :-D

**Comment by OlaHaldor** [comment]
Kan du ta opp video? Jeg har ikke fått rapporter om dette fra testere tidligere og har ikke erfart det samme.

**Comment by kandk1** [comment]
Hei igjen. Beklager om jeg stelte i stand unødvendig arbeid for deg, men jeg hadde glemt å kjøpe tomta. Pga place anywhere (antar jeg) fikk jeg plassert ut bygningen og da tenkte jeg nok ikke på at jeg likevel ikke kunne fjerne igjen. Testet nå på samme sted på eid tomt og i tillegg langt oppå snaufjellet i området man ikke får kjøpt og det funker som det skal der også.
