### ISSUE TITLE
Texture fault on field 88

### ISSUE THREAD

**Issue by BeardsViking** [MapsOfNorway/rennebugs#40]
Invisibel wall in middel of the field, tractor just stop agains a invisible wall and spinn. And i spike on the groun
![Skjermbilde (15)](https://user-images.githubusercontent.com/109419474/179421091-c9cdbd50-7053-4e8f-9767-ac99ed70ae2c.png)
![Skjermbilde (16)](https://user-images.githubusercontent.com/109419474/179421097-c0fd5402-3b00-49a4-ba68-4f869dd58d6f.png)
d

**Comment by odysseus-1** [comment]
Same thing happening on field 90. I could get through by going sideways
![Farming Simulator 22 7_18_2022 12_53_08 PM](https://user-images.githubusercontent.com/109550221/179588634-97fb445d-b261-4ad0-b9e6-b390420bfec8.png)

**Comment by OlaHaldor** [comment]
Thanks, this has been fixed. :)
