### ISSUE TITLE
Silage Silo

### ISSUE THREAD

**Issue by chulkr** [MapsOfNorway/rennebugs#41]
Har et problem med å få gress i silo fra forage henger, for produksjon av silage. 
Mangler grass til chaff conversion? eller er det spillet kanskje?

**Comment by OlaHaldor** [comment]
Kan du vise screenshot hvor du står?
Er det gress, høy eller chaff i hengeren?

**Comment by chulkr** [comment]
![20220718210156_1](https://user-images.githubusercontent.com/54313175/179599565-94ddf50f-be59-425d-a9cf-3daae88bf93b.jpg)

Silo bunker som ikke tar imot gress for produksjon av silage. Dårlig forklart på første post.
Har kjøpt original silo bunker fra shop

Den vil rett og slett ikke ta imot gresset

**Comment by OlaHaldor** [comment]
Funker det på andre mod kart? Default kart?
Prøv å start noen nye games.
Prøv også å start et nytt game med Rennebu bare for å teste.

**Comment by OlaHaldor** [comment]
Har funnet årsaken, og det blir fikset i en oppdatering av kartet.

**Comment by chulkr** [comment]
Kjempe greier! Fy flate for en jobb du har gjort med dette kartet! kudos
