### ISSUE TITLE
Black wall

### ISSUE THREAD

**Issue by Diagonax** [MapsOfNorway/rennebugs#42]
seems to be som kind of visual bug, i can walk inside. looks like some type of boulders with the wrong texture?

![image](https://user-images.githubusercontent.com/109482175/179421170-d40f3716-893f-4529-8dd6-9718737fad7a.png)

![image](https://user-images.githubusercontent.com/109482175/179421234-ec6cdb76-74ac-47d2-82dd-01090a5afce6.png)

**Comment by OlaHaldor** [comment]
I have only seen this the last couple of days, never seen it in any of my own test sessions or reported by beta testers.

Do you have other mods active?

**Comment by Jos-B** [comment]
I had this on test version. Back then it had no collision either. Looks like rocks from far away now and it has collision.

**Comment by Diagonax** [comment]
I have loads of mods, some of them could be interfering. No collision for me.
