### ISSUE TITLE
cant fill seed at felleskjøpet

### ISSUE THREAD

**Issue by lukasvri** [MapsOfNorway/rennebugs#43]
![image](https://user-images.githubusercontent.com/22594782/179422546-88e08051-6f9f-412a-8df8-e4def964b9cb.png)

**Comment by OlaHaldor** [comment]
Even if you open the cover?

**Comment by lukasvri** [comment]
yes

**Comment by OlaHaldor** [comment]
Ok. Yet another thing to check then.
I'm surprised though, never had issues in my own testing thus why I added this feature. 

Hang in there, I'll sort it out when I'm home.

**Comment by OlaHaldor** [comment]
It looks like the trigger box is just slightly too small. Try positioning the seeder different for now.
Will be fixed in a future update.

![image](https://user-images.githubusercontent.com/60529378/179861803-8dcf3c2f-a8b2-44b2-9671-29fcd4cbe823.png)

**Comment by OlaHaldor** [comment]
Fixed!
