### ISSUE TITLE
Kornmølle tar ikke imot soybeans.

### ISSUE THREAD

**Issue by Rubberduck1992** [MapsOfNorway/rennebugs#44]
No spare capacity for soybeans får jeg som error.
![20220717221823_1](https://user-images.githubusercontent.com/109314797/179423422-e118a360-f899-42b7-9dc6-1c0d14babb68.jpg)
r

**Comment by OlaHaldor** [comment]
Soyabønner produseres ikke til noe, så jeg anbefaler at du laster ned en mod hvor du kan selge alt mulig for å bli kvitt soya.
Mølla skal ta imot og produsere det aller meste i neste oppdatering.
![image](https://user-images.githubusercontent.com/60529378/181379938-ece1b526-8acd-4f1d-a890-740429c18a1d.png)
