### ISSUE TITLE
Fill triggers issues

### ISSUE THREAD

**Issue by PellaR** [MapsOfNorway/rennebugs#45]
hi. having some trouble with the fill triggers on the silage silo at the sheep barn and hay loft. can fill both silos but can unload only some times

**Comment by OlaHaldor** [comment]
Could you please show where you park the trailer when it's working/not working?

I've been told the trigger for the hay loft is a bit small or offset. I will fix this in an update.

**Comment by PellaR** [comment]
![fsScreen_2022_07_18_22_57_04](https://user-images.githubusercontent.com/41526082/179616765-17413363-896a-4bb0-a086-fdb55246bc8f.png)
![fsScreen_2022_07_18_22_59_13](https://user-images.githubusercontent.com/41526082/179616774-22f2a599-e85c-4ba5-80a4-6d36cabe0350.png)
here are some pics from the silage silo

**Comment by OlaHaldor** [comment]
Any chance you could record a video so I can see exactly what happens?

**Comment by PellaR** [comment]
Found out i have the same issue on other maps as well. So the problem is on my side

**Comment by OlaHaldor** [comment]
Do you use any mods when this occurs?

**Comment by PellaR** [comment]
It’s a mod conflict. Trying to find what mod it is at the moment
