### ISSUE TITLE
Production sellpoint is limited by internal storage

### ISSUE THREAD

**Issue by Jos-B** [MapsOfNorway/rennebugs#49]
Unowned productions will buy your product, but seem to be limited by the capacity of the productionPoint storage.

Suggestion: either add all crops to Joker or make a random building a sellingStation. If there is another place on the map, you can hide the production from the list!

This may cause problems for contracts too, could disable contracts for all productions:
`<productionPoint>
...
<sellingStation allowMissions="false">
`

**Comment by OlaHaldor** [comment]
Do you mean that the capacity is shared among all production points somehow (while you don't own any) ?
So if I made a random placeable with an astraonomical capacity, this would be fixed? 

OR

does it require to be available for players to sell there?

**Comment by hardcor3crash** [comment]
This mod fixes the issue. as long as the production point is not owned by a player all production point have unlimited capacity: https://farming-simulator.com/mod.php?lang=en&country=us&mod_id=241808&title=fs2022

**Comment by OlaHaldor** [comment]
I think this is fixed now. The building was missing a function to sell.
