### ISSUE TITLE
Field boundaries

### ISSUE THREAD

**Issue by odysseus-1** [MapsOfNorway/rennebugs#51]
I found parts of fields that are not recognized as the same field. It happened on contracts and the game didn't allow me to work there.

field 9 (the unharvested part to the left)
![Farming Simulator 22 7_17_2022 9_52_00 PM](https://user-images.githubusercontent.com/109550221/179599994-b1c16673-50d9-4563-8b21-af9beeaaf046.png)

field 5 (same problem)
![Farming Simulator 22 7_18_2022 12_50_30 AM](https://user-images.githubusercontent.com/109550221/179600161-dee42595-32e1-40b0-9280-eaad37b224aa.png)

field 37 (part on the left).The game reports my vehicle as being in field 36 "F-36 DEUTZ-FAHR..."
![Farming Simulator 22 7_17_2022 12_00_00 AM](https://user-images.githubusercontent.com/109550221/179601188-24394c83-798d-4b6a-bb81-40f1733e6b82.png)

field 91 (part to the top). Now it says I'm  in field 90.
![Farming Simulator 22 7_16_2022 3_25_49 PM](https://user-images.githubusercontent.com/109550221/179601626-cdb8a1c2-e5bf-4724-ba24-a98881315aca.png)

Many thanks for your map and for all your hard work to give as something really unique.

**Comment by BeardsViking** [comment]
I se the same in field 38 towards field 37. A smal strip that is on the field 38 belongs to 37 i get message about

**Comment by odysseus-1** [comment]
and another: field 33 (the white to the left can't be worked on)
![Farming Simulator 22 7_19_2022 1_39_08 AM](https://user-images.githubusercontent.com/109550221/179629290-bbf01d16-2e87-4496-bcb8-64909f08c893.png)

**Comment by OlaHaldor** [comment]
Having looked into these, I am at a loss of words. There's nothing I can visually see is wrong with these fields.

**Comment by OlaHaldor** [comment]
I have tested plowing on field 37 for reference. I don't experience anything close to what you're experiencing.
Are you running any mods that may have any impact on fields?

**Comment by gagorian82** [comment]
den bugen skjer ikke  før  du  har  spillt i noen timer  jeg  fixser det med  å  resterte  spille

**Comment by odysseus-1** [comment]
No idea why it was happening. With the same mods, I can work flawlessly on one of the fields I had problems before (field 5). This is after the update.
![Farming Simulator 22 8_9_2022 6_42_32 PM](https://user-images.githubusercontent.com/109550221/183700365-c2a25ed8-1c8a-4625-8c9e-6e046f0c30e5.png)

**Comment by OlaHaldor** [comment]
I'll close this then.
Make a new ticket if it occurs again.
