### ISSUE TITLE
Issue with syncing multiplayer 

### ISSUE THREAD

**Issue by kukfitte** [MapsOfNorway/rennebugs#52]
when you play multiplayer it's just synkronisng and cant get in. after i logged out 1 time

**Comment by OlaHaldor** [comment]
What does the log say?

**Comment by OlaHaldor** [comment]
Also changed the title to something more descriptive

**Comment by OlaHaldor** [comment]
I suggest you report this as a bug to Giants, either way I'm not able to fix things that are outside the scope of a mod/map.
Report it here 
https://feedback.giants-software.com/
