### ISSUE TITLE
Somting strange with the wether

### ISSUE THREAD

**Issue by BeardsViking** [MapsOfNorway/rennebugs#53]
Se the video https://youtu.be/bPBczKF-s8g

**Comment by OlaHaldor** [comment]
Can't see the video, it's marked private. Make it unlisted so I can see. :)

**Comment by BeardsViking** [comment]
My bad 😂 Try now

**Comment by OlaHaldor** [comment]
What did you do before this happened?
I have never seen anything remotely like such unless I 
- jump forward in time with console commands
- Speed up the game way past the default speeds
- Sleep

Even if I do any of the mentioned, it does not glitch like this for long, and that is the same regardless of what map I play on.

If you load the save again, does it continue?

**Comment by BeardsViking** [comment]
I was at the house and take a nap to the next morning. After I wake up this happend.

**Comment by OlaHaldor** [comment]
Alright, interesting. Not sure this is Map specific though even if this is the first time you encountered it. If it is, I'm not sure what I could do about it anyway. I suggest you post the bug report at Giants as well. 

You report bugs about the game here 
https://feedback.giants-software.com
