### ISSUE TITLE
Fields and ingame weather

### ISSUE THREAD

**Issue by Olechr04** [MapsOfNorway/rennebugs#54]
I've turned off the field stone ingame, and I have been going in and out of the game manybtimes but it still Stones on two of my fields🤔 but not on the other two. 

I'm also wondering why its snowing when im in May month🤔

**Comment by OlaHaldor** [comment]
Snow in may is not unheard of in Rennebu. Welcome to the mountains. :D 

The field stones issue is not map specific. As far as I know the same can happen in any map, default or mod map, because if there's stones present already they don't just magically go away when you change the setting.

**Comment by Olechr04** [comment]
> Snow in may is not unheard of in Rennebu. Welcome to the mountains. :D
> 
> The field stones issue is not map specific. As far as I know the same can happen in any map, default or mod map, because if there's stones present already they don't just magically go away when you change the setting.

Aha, okay. Nice to know:)
