### ISSUE TITLE
Bruholt hayloft trigger

### ISSUE THREAD

**Issue by JanR73** [MapsOfNorway/rennebugs#59]
Trigger for loading from hay loft is very close to the wall. can´t load into side of trailer only into back.

![fsScreen_2022_07_20_11_33_55](https://user-images.githubusercontent.com/109307501/179950220-76ce13af-8272-4371-a5f7-9225cc07594f.png)
.

**Comment by OlaHaldor** [comment]
Trigger has been made larger. Can now be loaded from the side as well.
