### ISSUE TITLE
Black wall

### ISSUE THREAD

**Issue by Sanstensrud** [MapsOfNorway/rennebugs#62]
A black wall appers north of the staring farm. I have tried to disable all mods, but it did not change anything.

**Comment by OlaHaldor** [comment]
It's been reported twice before you, so I'm sure it's quite rare.
What one of the others did was delete the map and re download it. See if that helps.

**Comment by OlaHaldor** [comment]
I am testing on a Mac right now and I Can confirm it is indeed black there. 
Are you on Mac or Windows? 

![image](https://user-images.githubusercontent.com/60529378/180023398-7b7646bd-44c6-43f1-87c1-39fef8924624.png)

**Comment by Sanstensrud** [comment]
I play on windows.

**Comment by OlaHaldor** [comment]
Has this been resolve for you?
Do you have any mods active, if so, which ones? Could you disable them? 

What's your graphics settings?

**Comment by OlaHaldor** [comment]
Closing this one as the issue is old and haven't heard back from you.
If you still experience this, please open a new ticket with more information about your hardware and graphics settings.
