### ISSUE TITLE
Strange pattern after sowing

### ISSUE THREAD

**Issue by BeardsViking** [MapsOfNorway/rennebugs#64]
This is on field 45
![Skjermbilde (22)](https://user-images.githubusercontent.com/109419474/180081415-180d84cb-c5a9-43cd-bde0-ba838cbf45e7.png)

**Comment by OlaHaldor** [comment]
Does this happen on all fields everywhere?
What's the ground like? Fertilized? Prepared somehow with cultivator? Anything else?

**Comment by odysseus-1** [comment]
The headlands have these different shades of brown. To the left it's the lighter shade. When you start there you draw a light brown seeding line. When you reach the darker brown headland you raise the seeder and start a new line. Now it's darker brown.

Why the headland on one side is different? I am not sure in this case, but it always happens to me when I start seeding with  the wrong crop and go over it and reseed.

**Comment by OlaHaldor** [comment]
It looks similar to an issue with fertilizer and the resolution of an infolayer file I had right before submitting the map.

**Comment by BeardsViking** [comment]
The field are harrowd and limed before sowing. But it had some weed

**Comment by MariusTro** [comment]
I have noticed that when using precision farming and you have analysed your "big starting field" it does not cover all of it with lime. On the minimap it is covered but on the field itself there are dark spots that is not covered with lime.

There is also issues with the rows of gras after you use the windrower. They are not straight at all for some reason. I am thinking this is linked with the weirdness OP writes about.

**Comment by OlaHaldor** [comment]
> There is also issues with the rows of gras after you use the windrower. They are not straight at all for some reason. I am thinking this is linked with the weirdness OP writes about.

That's the result of the map being big, with no room for increased resolution in the files that hold information about things such as windrows.
If you go in perfect 90 degree directions (north/south/east/west) they will be straight. As soon as you deviate from that, they will be 'rough', just like the ground textures.

**Comment by OlaHaldor** [comment]
I have made a new savegame with precision farming, analyzed the field which was cultivated.
I have a seeder with fertilizer and I have no issues like you show above.

I wonder; does the issue you see happen after a long time? 
If it's a server, when was it last restarted? Try restarting the server and see what happens.

If it was singleplayer, how long is the game session before it happens?

**Comment by MariusTro** [comment]
It was singleplayer. I have not cultivated it in the playtest. Gras grow so
fast it is almost ready for harvest again when I use rower and baler. Using
6x and 3 days a month. So test it only as it is when you start a new game
with grass ready to harvest. My guess is that it wont be a problem if you
cultivate the field.

fre. 5. aug. 2022, 09:10 skrev OlaHaldor ***@***.***>:
