### ISSUE TITLE
No reproduction at Nørigard cowfarm

### ISSUE THREAD

**Issue by BeardsViking** [MapsOfNorway/rennebugs#65]
The reproductin graph go up to 100% and then start on 0 again with no reproduction

**Comment by BeardsViking** [comment]
Will test when I'm home from vacation

**Comment by OlaHaldor** [comment]
What kind of cows is it?

**Comment by OlaHaldor** [comment]
Alright, I've made some changes to the map actually. The cow feed will be something like this
TMR (20%)
Silage (50%)
Hay, grass and chaff (30%)
