### ISSUE TITLE
AI traffic stuck (different spot)

### ISSUE THREAD

**Issue by odysseus-1** [MapsOfNorway/rennebugs#66]
Traffic stops here too, for no reason.
![Farming Simulator 22 7_19_2022 2_22_55 AM](https://user-images.githubusercontent.com/109550221/180147940-1a180a63-8ac4-4dfc-be49-9f0877c00db3.png)

**Comment by OlaHaldor** [comment]
Known bug. Will investigate.
If it's too annoying, turn traffic off for now.

**Comment by OlaHaldor** [comment]
Removed the traffic spline for this turn. Should not happen again.
