### ISSUE TITLE
Invisible barrier (between fields 20-21)

### ISSUE THREAD

**Issue by odysseus-1** [MapsOfNorway/rennebugs#68]
The tractor stopped
![Farming Simulator 22 7_19_2022 2_57_29 PM](https://user-images.githubusercontent.com/109550221/180149515-8e9d4c68-af66-4153-a192-f8b6c05db8e7.png)

The seeder stopped (same spot)
![Farming Simulator 22 7_19_2022 2_58_04 PM](https://user-images.githubusercontent.com/109550221/180149620-3e68a3b3-9481-45cd-ba20-dfaf3f803032.png)

**Comment by OlaHaldor** [comment]
My bad. There's a tree that's been hidden.
Fixed.
