### ISSUE TITLE
Can buy seeds only at the mill

### ISSUE THREAD

**Issue by odysseus-1** [MapsOfNorway/rennebugs#69]
I tried every approach, I only get seeds. Even here
![Farming Simulator 22 7_19_2022 9_16_04 PM](https://user-images.githubusercontent.com/109550221/180150146-2e7371f4-75b4-460b-a620-62a01ab2ba93.png)

**Comment by OlaHaldor** [comment]
I will take care of it in an update when I'm back from vacation

**Comment by OlaHaldor** [comment]
Turns out this is gonna be a tricky one. Might have to make separate buy stations per product. It will take a little more time and careful execution.

**Comment by marimba2112** [comment]
I tested this out a little more. It seems to be able to dispense seeds, lime, and liquid fertilizer (I did not test solid fert but I will assume that I can given the right conditions). What I found is that one is unable to choose from among different items when your trailer/tanker/spreader, etc can be filled with more than one of the items. For example, when I used a bulk trailer (accepts seeds, solid, fert, lime) all I could get was seeds. Even if I partially prefilled the trailer with something else (e.g. solid fert) it would be replaced with seeds.
Using a tanker that accepts all liquids, I can get it to dispense liquid fertilizer no problem).
When using a spreader that accepts both solid fert and lime, I could only it to dispense lime.

Ola, it seems that if one were given a menu to choose from available items that can be dispensed in the receptacle that triggered the event, this would be the optimal solution and is how other maps have approached this scenario.

**Comment by OlaHaldor** [comment]
I completely agree about the menu. It's been a long time since I added this, but I believe I did have a menu before and I wonder if something changed with the game since in updates.

there's no easy way I can just simply add an attribute "show that menu" sadly. Will have to figure out how to deal with this.

**Comment by OlaHaldor** [comment]
Note to self: make multiple placeables with specific buy stations. For a future update.
