### ISSUE TITLE
Animals Opposite f44 - Fill Plane Issues

### ISSUE THREAD

**Issue by NdMoreSpd** [MapsOfNorway/rennebugs#7]
![image](https://user-images.githubusercontent.com/85452846/179096830-3f3e8ca0-414f-45a4-a4ab-d04ab5d1eecc.png)
As noted in image the fill plane for the straw in the horse pen appears elevated.
Unable to find a water fill point for the horses.
Unable to find a straw point for the cows.

**Comment by OlaHaldor** [comment]
Moved the straw planes.
