### ISSUE TITLE
Field Boundary

### ISSUE THREAD

**Issue by Tarathox** [MapsOfNorway/rennebugs#71]
Field boundary is wrong between field 78 and 79
get message that i don't have access on the lime part

![20220722000932_1](https://user-images.githubusercontent.com/109768869/180325125-a18be071-fd4d-4f65-b2a3-a20c021170c6.jpg)

**Comment by gagorian82** [comment]
har  hver  borti det same  probelme  på mange  åker  etter noen timer med spiling.  men løser det med  å resterte  spille  håper  infon hjelper  for meg ser det  ut som åker biding  boxs  kryper eller  flyter på seg etter noen timer  med spilig  og  åker  86 og 87  har  courseplay  problemer  å se  som to  åker  dem ser dem som en åker

**Comment by OlaHaldor** [comment]
Hmm this will be a tricky one if it's truly a problem.
Never heard of it or experienced this myself before.

The fields are clearly separate. 
![image](https://user-images.githubusercontent.com/60529378/181852889-3ab75497-01a9-421f-bef1-2ecf6a0eaef6.png)

**Comment by OlaHaldor** [comment]
I checked farmlands too. Both of the fields are owned by the same farmland. So this is a real pickle.
