### ISSUE TITLE
Cow barn with feeding robot 

### ISSUE THREAD

**Issue by AsgeirBers** [MapsOfNorway/rennebugs#72]
Cow barn with feeding robot doesnt seem to give milk. Productivity on 0% and Health, altough they got all they need.
Have tested on other maps and it seems to be an issue with this map.

![20220724020729_1](https://user-images.githubusercontent.com/109881470/180626787-0c1531bf-bc51-4a1e-8f5b-bf558d00241b.jpg)
![20220724020610_1](https://user-images.githubusercontent.com/109881470/180626788-a8c1e2cb-d0d4-45a1-b35d-78f65becec61.jpg)

**Comment by OlaHaldor** [comment]
Food will change a little in a future update.

**Comment by OlaHaldor** [comment]
You will need to feed the other food types too. TMR is sort of a little bonus but not required. Silage is the main kind of feed irl, supplemented with grass, hay and chaff.
