### ISSUE TITLE
bug med trær 

### ISSUE THREAD

**Issue by bakken2022** [MapsOfNorway/rennebugs#73]
får opp meling om at jeg ikke kan kappe trær 
selv om at jeg kan det

**Comment by OlaHaldor** [comment]
Har du mer info?
Hvor? Eier du eiendommen?
Singleplayer eller multiplayer?

**Comment by bakken2022** [comment]
Multiplayer det stede man eier vis man starte på lett der området der får ikke lakt til skjermbilder

**Comment by OlaHaldor** [comment]
Det blir dessverre vanskelig for meg å verifisere, og sjekke ut området for det du opplever om jeg ikke kan se.

**Comment by TheOnlyManatee** [comment]
![FarmingSimulator2022Game 2022-07-25 15-50-27](https://user-images.githubusercontent.com/109970529/180795806-db12ad8e-6855-4303-9083-ce96042372c5.png)
![FarmingSimulator2022Game 2022-07-25 16-01-09](https://user-images.githubusercontent.com/109970529/180795834-2d499b5b-3dd7-4392-ac1a-bb5776ea3986.png)

Har samme meldingen, ser ut til å komme før du går bort til treet, ikke når man kapper, så lenge man går med saga ute. Testet i flere eide områder, de kan kappes, men meldingen blinker av og på. 
Er også noe rart med trær i området på skjermbildet, hadde ikke det problemet i området man starter med. Kollisjonen til trærne ser ut til og være forskjøvet litt, man må sikte rundt en meter utenfor. Var konsekvent i det området, med ikke en annen plass jeg testet. Trærne hadde heller ikke kollisjon som forventet når de var hogd ned. Deler av de clipper gjennom bakken/kjøretøy. 
Dette er i singleplayer.

**Comment by OlaHaldor** [comment]
Kollisjon på trærne har nok en feil ja. De fleste trærne er av de som lagde Holmåkra, og de oppdaget en feil med de.

Det har de fikset nå, og jeg skal oppdatere med trærne deres i en oppdatering av kartet.

Lurer på om den feilmeldingen er på grunn av de problemene med trærne også.
Hvis det ikke er det som er problemet er jeg ærlig talt ikke sikker på om det er noe jeg kan fikse.

**Comment by XullerTull** [comment]
Mulig også en bug med 1.6 av Farming. Last ned Lumberjack modden, den har en midlertidig fix.

Fra lumberjack updatelog:
v1.3.0.0
- Using new "permission to cut trees" multiplayer feature in v1.6

**Comment by OlaHaldor** [comment]
Har ikke dette problemet etter jeg oppdaterte med nyeste versjon av trærne fra Holmåkra.
Gi gjerne lyd her igjen med en ny melding etter at oppdateringen er live på Modhub dersom problemet fortsetter.
