### ISSUE TITLE
Contract error

### ISSUE THREAD

**Issue by ohlssrog** [MapsOfNorway/rennebugs#74]
Fields are merge into each other on contracts and  u get error what u don't own the land and cannot complete the job. Exampel on fields that merge are 59-63, 
![filds_error](https://user-images.githubusercontent.com/34940036/180655780-f9e2fa24-e053-4a4d-986e-ae33440d4e5d.PNG)
.

**Comment by OlaHaldor** [comment]
Technically nothing wrong here. Honestly not sure what I can do about it.
All fields have an artificially huge border. Irl they are separated by just bushes or some tall grass, literally overlapping. 

This is fields 59 and 63. As you can see the border between the two is many meters.
![image](https://user-images.githubusercontent.com/60529378/182003683-3e8fa4f5-b07c-4afe-b5b4-b879c1423790.png)
