### ISSUE TITLE
De e ikke collision på mølla her.

### ISSUE THREAD

**Issue by Makkus08** [MapsOfNorway/rennebugs#75]
![image](https://user-images.githubusercontent.com/109968073/180787717-6190a0fa-d1f9-4a85-a026-ff6feba34bdd.png)
![image](https://user-images.githubusercontent.com/109968073/180787777-f312166c-7b13-4cac-85b5-966e6eb42055.png)

De e ikke collision på mølla her

**Comment by OlaHaldor** [comment]
Fixed
