### ISSUE TITLE
Cows dont produce anything

### ISSUE THREAD

**Issue by Andre0305** [MapsOfNorway/rennebugs#77]
Hello i have 95 cows on rennebu and i've had them for 1 year+ and they have totaly produced 1700 liters of milk i have feed them with Tmr and added straw i dont know if it is a map issue but i play on dedicated server.

**Comment by OlaHaldor** [comment]
I have made some changes to food. Will test this more thoroughly before releasing the update.
Rest assured, I want this to be fun and rewarding :)

**Comment by OlaHaldor** [comment]
What kind of cows is it?

**Comment by Andre0305** [comment]
the cows is holstein

**Comment by OlaHaldor** [comment]
Did this change with the update?

**Comment by OlaHaldor** [comment]
I have tested on a random barn now. If the barn is full, obviously it won't produce new cows.
If there are empty slots they will reproduce.
