### ISSUE TITLE
Saving takes along time

### ISSUE THREAD

**Issue by MariusTro** [MapsOfNorway/rennebugs#78]
I am having issues with saving taking between 30-45 seconds. This is the only map I have this issue with. I have tested other really big maps too and they save fast. 

Yes I am running the  game on M.2 disc and everything is up to date. New and fast computer.

**Comment by NMC-TBone** [comment]
Would it be possible to see your log.txt? This map is large so longer save times is of course expected, but 30-45 seconds may be a bit over what one could expect for sure.

**Comment by OlaHaldor** [comment]
Even if it's an M2, they come with different write speeds, and without knowing more about your hardware it's hard to pinpoint whether you're experiencing some sort of bottleneck. 

There is Literally nothing I can do to improve this. The map is as optimized as can be. 
This is more a matter for Giants, but frankly not sure what they could do either.

**Comment by MariusTro** [comment]
I did a bit more testing. I found my stopwatch and timed it. Saves with or without the mods I am running at 25 seconds. Not as long as 45 but it feels long. But I have been testing other big maps like "The French Plains" that is a very very big map also in megabytes. This maps saves in 4 seconds with or without mods. I have literally tested every huge map I have found and all around 4 seconds. 

I can tell you how fast my M.2 is saving since I have just tested it. 4950 MBps (read) / 4250 MBps (write) 

But like I said I have no issues on any other map. It may be my computer but it is not my M.2 hdd thats causing it. I still find this weird.

**Comment by OlaHaldor** [comment]
My first thought then is the vast amount of trees. There's somewhat between 160-180K trees in total. I guess writing data about those might cause long saves too 🤷🏻‍♂️

What's the size of the French map?

**Comment by MariusTro** [comment]
In mb size its 514 mb and rennebu is 483 mb so I guess it is similar. But yes "The French Plain" does not have many trees. When it comes to how big the map is to drive across I do not know. Not tested that. But it takes a long time on both maps so I guess they are similar. My guess is that the amount of trees cause this too. However if it is only me that experience this then I would not bother trying to figure it out. I can live with it. :)
