### ISSUE TITLE
Bergtun - Wool production area

### ISSUE THREAD

**Issue by MariusTro** [MapsOfNorway/rennebugs#79]
The two outer pallets with wool are placed partly outside the production area. It does not look aligned. Not a big issue.

Also cannot access the prodution of wool at bergtun? I can see silage production but not wool production.

**Comment by OlaHaldor** [comment]
Production of wool has nothing to do with productions as with a factory. 
If you mean the stats that should show up in the lower right, that's unfortunately a result of merging two building types: _animalHusbandry_ and _production_.

The game does not know which info to show, thus the entire building will print errors in the log. I will have a chat with Giants and see what they can say about the matter. I would absolutely like to have the info show up for both the production of silage, and for the sheep.
