### ISSUE TITLE
When it rains the rain falls inside of the sales office shed. 

### ISSUE THREAD

**Issue by marimba2112** [MapsOfNorway/rennebugs#83]
It could be same problem inside other structures but I haven't checked them.  This is ScottFree4all BTW

**Comment by OlaHaldor** [comment]
Do you know for a fact this happens in other buildings? If so, please attach a screenshot too and it'll be easy for me to check the specific building. 

You can take a screenshot and copy-paste directly in this text editor, you'll know when it's uploading.

**Comment by Dylan-M** [comment]
At a guess, it would probably affect all of these buildings that are supposedly missing roof collisions reported here:
#111
