### ISSUE TITLE
Rennebu/Building of norway

### ISSUE THREAD

**Issue by smartinius** [MapsOfNorway/rennebugs#87]
lasta ned dei "testing" filene dine på discord, og tok ut dei 2 andre frå mod mappa. gjekk inn på spelet så var savegamen svart bakgrunn på og når eg prøvde å gå inn på så krasja spelet. 
konklusjon: bugsfixes? ny fil? går ikkje ann å gå¨inn på samme savegame med dei nye filene!  vertfall ikkje slik det er no

kjemep bra map og byggningspakke, sjølvsagt små detaljer eg og kunne tenkt meg, men ka faen? ekje det slik at alt kunne vore bedre? Alltid?
eg e fornøgd med mappet og byggningane! STOOOOOR Respekt for deg og fyttit katta du har vore flink og ikkje minst lagt mykjt tid idette her!
Keep up the good work 👍

**Comment by OlaHaldor** [comment]
Da har det skjedd noe feil på din side. :)
Mange andre har testet, og jeg har selv testet på en annen maskin at dette skal gå fint. 

Nå ligger i midlertid oppdateringene klar til å publiseres i modhub. Regner med de kommer i dag. :)
