### ISSUE TITLE
Sauene er vanskelige og gi mat

### ISSUE THREAD

**Issue by OkTimeForBed** [MapsOfNorway/rennebugs#88]
Saue innheiningen fra buildings of norway kan bare mates med telehandler eller lignende da hengere ikkje kan rygges inn til trigger. Kan heller ikkje tømme rett på bakken og sende det ned i conveyor belt

**Comment by OlaHaldor** [comment]
Takk for innspill, du belyser en problemstilling jeg ikke har tenkt på.

skal undersøke hva som kan gjøres med saken. Å bruke samlebånd hadde jo vært litt gøy!

**Comment by OkTimeForBed** [comment]
![image](https://user-images.githubusercontent.com/110506365/182685239-555ad2f9-0466-42c3-a32b-603f908393ab.jpg)
Ja kommer som sagt ikkje til med noe annet en traktor og frontlaster😃 i og med dyrene trenger mye mat så tar det litt tid og fore dem. (45min) så skulle fått til og sendt det ned ved enten og sette trigger i midten av låven eller kansje gjøre slik man kan tømme lasset i midten av låven for så og bruke eit samlebånd for og få det ned i triggeren

**Comment by OlaHaldor** [comment]
Jeg kan se på om jeg kan gjøre triggeren større uten at det påvirker så mye annet. Noe av problemet jeg ser for meg kan oppstå er at man kjører forbi med rundball som skal lagres, men så blir den i stedet tømt oppi til sauene.

Jeg skal se på saken.

**Comment by OlaHaldor** [comment]
Da har jeg gjort triggeren større så det blir lettere å tømme.
Kommer med i en senere oppdatering.
