### ISSUE TITLE
Questions on update 1.1

### ISSUE THREAD

**Issue by judg393** [MapsOfNorway/rennebugs#89]
Your recent Change log says you've disabled a number of crops. If I have production buildings that produce the crops (oma tanas open garden pack) can I still use those crops? I just can't grow them? Is that right 

Secondly out of interest if you've disabled maize (corn) how do we get chaff for cows?

**Comment by judg393** [comment]
Also has anyone else reported problems with harvest contracts not generating enough crop to complete? It may be another mod or a game issue over the map but just thought I'd check

**Comment by OlaHaldor** [comment]
I'm not sure what happens with existing buildings with these crops. That's not a use case I can test for, as I can't support more than what I make myself. 

If the buildings are for animals; they will only use what the map allows.
If the building is used for production or selling, you can use what remains you have of the crop type as far as I know, if you have something in a silo which you can load into a trailer.


How do make chaff without corn; by default the game can make chaff from the following
_MAIZE_ **WHEAT BARLEY OAT CANOLA SUNFLOWER** _SOYBEAN_ **SORGHUM**

So you have a lot of options available to you.

**Comment by OlaHaldor** [comment]
> Also has anyone else reported problems with harvest contracts not generating enough crop to complete? It may be another mod or a game issue over the map but just thought I'd check

I've seen similar reports. The solution seems to be to restart the game. It may be something drifting over time. I can't tell technically what's going on but I don't think this is a map problem but something Giants should have a look at.
They may or may not do anything about it because the map exceeds far beyond their own supported map size.

**Comment by judg393** [comment]
Ooo thanks and yes I completely forgot about whole crop silage option  😂 sorry that's my bad. I will just test out the production building and see :) 

Also I will try the game stop and restart. 

Just reread my comment and I hope you weren't offended by any of my comments I wasn't intending to come across mean but fear I may have done. I think this map will be my home for many many hours you can tell it's a real labour of love!
