### ISSUE TITLE
Cannot see soyabeans after update

### ISSUE THREAD

**Issue by ohlssrog** [MapsOfNorway/rennebugs#90]
After 1.01 update i cannot see any soyabeans in the season calander

![fsScreen_2022_08_03_20_51_07](https://user-images.githubusercontent.com/34940036/182686918-a88b8e7b-1316-4b53-a0c7-d33db50270c5.png)

**Comment by OlaHaldor** [comment]
That is intended. Soy beans is not grown in the area irl. Same with sugar canes and corn.
