### ISSUE TITLE
Bruholt hayloft trigger (new)

### ISSUE THREAD

**Issue by odysseus-1** [MapsOfNorway/rennebugs#91]
Cannot find the trigger to load (new save game with updates). Isn't it supposed to be bigger now? Or is it too low for big trailers?

![Farming Simulator 22 8_3_2022 11_40_56 PM](https://user-images.githubusercontent.com/109550221/182708525-78c7ff32-32ee-443e-8fb4-7ff4a1569b44.png)

**Comment by OlaHaldor** [comment]
The trailer might be too big by the looks of it. I will have a look.

**Comment by OlaHaldor** [comment]
I'm closing this one without any changes. The trailer is basically too large for the building.
