### ISSUE TITLE
Tipcollision not updated in old savegame with 1.0.0.1

### ISSUE THREAD

**Issue by Laserkari** [MapsOfNorway/rennebugs#92]
I started a savegame on original map version, and updated to 1.0.0.1 from modhub. But tipcollision problems are still present on the old savegame. On a fresh started save it works on the new map version. Have not tested bunker silos, but wanted to store woodchips on the ground/tipcol storage for a placeable heating plant but get the "This action cannot be performed here!" error. When I drive a around, I can find small spots wher to tip small amounts though.
[https://cdn.discordapp.com/attachments/1002205815496769647/1004525976996282479/111.png](url)

I've tried all that I could think of how to reset the tipcol but cant get it to change within the old savegame. Its changed now from FS17 I see. Then you'd just delete the tipCol.grle from savegame,  and a new was generated from the map files, but now with FS22 there seem to be revision marks of it on map.xml, and in the careerSavegame.xml file too.. Beyond my skills for now.

The old savegame, saved with new map version from server: https://drive.google.com/file/d/1kkG2SpDHmGEycJSOQDW48dMf0qxFyB3X/view?usp=sharing

**Comment by OlaHaldor** [comment]
Pasted the screenshot in here for easier access.
You can copy-paste directly into the text editor and it will upload the screenshot. :) 
![image](https://user-images.githubusercontent.com/60529378/183072758-93e98dd4-f4f9-4455-82b1-2d9b63db6951.png)

**Comment by OlaHaldor** [comment]
Well this is interesting. :) I loaded your savegame and I can tip there.
![image](https://user-images.githubusercontent.com/60529378/183073602-3a627c7a-f2a1-485b-b595-bc5f5a75a124.png)

**Comment by Laserkari** [comment]
I'll try to look into it more then. And try find out why its not updated for me. Can you save it in your end again and share? And I will do some compare whats happening on my end.

**Comment by OlaHaldor** [comment]
I'm away for a couple days. 
I found an issue with another player where tipCol is fine but there is another, tipColGenerated which is the culprit.
I'll see if I can send you the file through the phone.

**Comment by OlaHaldor** [comment]
Have you had a chance to check with the new tipcol files I sent?

**Comment by OlaHaldor** [comment]
An update, soon to launch. You can decide whether to keep the old savegame or start a new, but as shown above this should work. Closing the ticket. :)
