### ISSUE TITLE
Health and reproduction for animals seem to be broken. 

### ISSUE THREAD

**Issue by Rubberduck1992** [MapsOfNorway/rennebugs#94]
It always says 0% for me and cows are not producing milk.
![image](https://user-images.githubusercontent.com/109314797/183149762-37868fa7-adcd-4b9f-ad41-78fea2bc5275.png)

**Comment by MariusTro** [comment]
I have seen this too. Isnt health linked to how clean the feed area is? Or was this only a thing in FS19 where you had to use a broom to clean?

**Comment by OlaHaldor** [comment]
You are on an old version.
In general the animals need more than TMR.
Feed them the other types too.

**Comment by b-gyula** [comment]
This should be mentioned somewhere, because in the original barns grass **OR** hay is required for sheeps, whereas in these it seems **BOTH**!
Anyways congrats and _*BIG THANK YOU*_ for the map! It's amazing!

**Comment by OlaHaldor** [comment]
> 

Should be mentioned as sort of a manual on how to play the map, or do you applaud it as a good thing? :) 
I wantedto stay true to the region. I don't know how sheep are fed elsewhere, but in Norway it's quite common to give both, and other food that's not part of the game by default.

**Comment by b-gyula** [comment]
Well I'm not saying it is a good or a bad thing, and if your region has this way of feeding sheeps, it's fine. I think the original pig barns behave the same way. Just mention it in the description of Buildings Of Norway mod would be nice.
