### ISSUE TITLE
Ground going through floor on Lökkja Barn when placed

### ISSUE THREAD

**Issue by GurrraNN** [MapsOfNorway/rennebugs#96]
I was placing the Lökkja barn on my farm and the ground just kept going through the floor (even after leveling several times and dropping the ground in the back before placing etc)
![fsScreen_2022_08_06_00_20_36](https://user-images.githubusercontent.com/110699419/183219225-482d16d3-5daa-4969-a089-72a519fc60b7.png)

**Comment by OlaHaldor** [comment]
Noted. Will check and fix the level area.

**Comment by OlaHaldor** [comment]
Fixed. Available in a future update.
