### ISSUE TITLE
Grass Growth broken?

### ISSUE THREAD

**Issue by MariusTro** [MapsOfNorway/rennebugs#97]
I am seeing issues with grass growth. I cut the grass and sleep 2 times and then it is ready to harvest again? I first started to notice this on a big field where I used several ingame days (3 days a month setting) to cut and collect the grass on a big field. Before I was able to finish collecting the grass it was ready to be harvested again? Is this broken by Giants or is this a map issue?

Edit: I have tested other maps it seems it must be a feature from Giants as it is the same on all maps for me. I have tested without any mods so it is not a mod conflict. Anyone got this issue or is it just me?

**Comment by OlaHaldor** [comment]
I've had this across the board in default maps too in both 19 and 22. Not sure there's much I can do specifically. The fields are big of course so perhaps you could divide a few fields to smaller fields and harvest them one after another if this is a big issue.
