### ISSUE TITLE
FPS drops and flickering inside cabin. 

### ISSUE THREAD

**Issue by Marueki** [MapsOfNorway/rennebugs#98]
I have huge FPS drops to 40 sometimes. I also get flickering when tractor is going towards road or river. It happens with all vehicles. This never happen in other maps.
i7 9700
Rtx 2080s
16GB RAM 

https://youtu.be/Vz5woxjFIdw

**Comment by OlaHaldor** [comment]
I've always had decals and screens flicker regardless of map. Nothing I can do about that specifically for Rennebu as it is not tied to the map.

There's very little I can do to make your frame rate better. It is a huge map, 16 times larger than the default. There's over 150K trees. There are over 140 fields. There's so much going on in tender and in the background.

The only way to improve performance is to 
- get better pc parts 
- Lower settings
- Delete trees
- Make a smaller map


The latter two is not possible on this map.
Future maps I make will not be this big.

**Comment by Marueki** [comment]
Ok. Thats what i figured too. Its still a very beautiful map!
