### ISSUE TITLE
TMR at Cowbarn

### ISSUE THREAD

**Issue by Micke321** [MapsOfNorway/rennebugs#99]
I can´t give the cows TMR att the Bergtun Cow Barn. But Straw, Hay and Grass goes fine.

**Comment by OlaHaldor** [comment]
Is it full of food?
Can you share a screenshot of the instant where you cannot deliver TMR?

**Comment by Micke321** [comment]
I found out you need to be really close to the marker for it to work..

**Comment by OlaHaldor** [comment]
What version are you on?

**Comment by Micke321** [comment]
The lates one in FS22 downloads..

**Comment by OlaHaldor** [comment]
Ok, just to make sure: you downloaded through Modhub, right? Not some third party site?
And the version of buildings of norway is 1.0.0.1 ?

**Comment by Micke321** [comment]
![2022-08-07 (2)](https://user-images.githubusercontent.com/110761538/183304930-424654ab-dcc9-49c9-b50c-c487997beef5.png)
This close i need to be..  
The version is 1.0.0.1 :) Always download to modhub..

**Comment by OlaHaldor** [comment]
Ah, I see. Always new use cases I've not thought about. :) 
Will certainly have a look at that for a future update.
